'use strict';

const defaults = {
	host: 'http://localhost:7700',
	apiKey: undefined,
	maxDocuments: undefined,
	indexed: false,
	rankingRules: [
		{ rule: 'words' },
		{ rule: 'typo' },
		{ rule: 'proximity' },
		{ rule: 'attribute' },
		{ rule: 'sort' },
		{ rule: 'exactness' },
	],
	stopWords: [],
	typoTolerance: 'on',
	typoToleranceMinWordSizeOneTypo: 5,
	typoToleranceMinWordSizeTwoTypos: 9,
	typoToleranceDisableOnWords: [],
	synonyms: [],
	healthCheckInterval: 60,
	searchMinTermLength: 2,
	globalChatSearchEnabled: 'on',
	semanticSearchEnabled: 'off',
	semanticSearchProvider: 'openAi',
	semanticSearchApiKey: undefined,
	semanticSearchModel: undefined,
	semanticSearchUrl: undefined,
	semanticSearchDimensions: undefined,
	semanticSearchRatio: 0.5,
	semanticSearchScoreThreshold: 0.2,
	semanticSearchRestRequest: undefined,
	semanticSearchRestResponse: undefined,
	// Internal bookkeeping (not an ACP field): last embedder config actually pushed to
	// Meilisearch per index, so unrelated settings saves can't re-trigger paid re-embedding.
	appliedEmbedders: {},
	lastReindexResult: {
		success: false,
		finishedAt: null,
		topic_progress: { current: null, total: null },
		post_progress: { current: null, total: null },
		message_progress: { current: null, total: null },
		skippedDeletedTopics: 0,
		skippedDeletedPosts: 0,
		skippedDeletedMessages: 0,
		skippedSystemMessages: 0,
		skippedOrphanMessages: 0,
		error: null,
	},
};

const breakingSettings = [
	'maxDocuments',
	'rankingRules',
	'stopWords',
	'typoTolerance',
	'typoToleranceMinWordSizeOneTypo',
	'typoToleranceMinWordSizeTwoTypos',
	'typoToleranceDisableOnWords',
	'typoToleranceDisableOnAttributes',
	'synonyms',
	'semanticSearchEnabled',
	'semanticSearchProvider',
	'semanticSearchApiKey',
	'semanticSearchModel',
	'semanticSearchUrl',
	'semanticSearchDimensions',
	'semanticSearchRestRequest',
	'semanticSearchRestResponse',
];

module.exports = { defaults, breakingSettings };
